/**
 * generated by Xtext 2.22.0
 */
package jope015.mdsd2021.reexam.cMSdsl.impl;

import jope015.mdsd2021.reexam.cMSdsl.Bool;
import jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bool</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BoolImpl extends DataTypeImpl implements Bool
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BoolImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CMSdslPackage.Literals.BOOL;
  }

} //BoolImpl
