/**
 * generated by Xtext 2.22.0
 */
package jope015.mdsd2021.reexam.cMSdsl.impl;

import jope015.mdsd2021.reexam.cMSdsl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CMSdslFactoryImpl extends EFactoryImpl implements CMSdslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static CMSdslFactory init()
  {
    try
    {
      CMSdslFactory theCMSdslFactory = (CMSdslFactory)EPackage.Registry.INSTANCE.getEFactory(CMSdslPackage.eNS_URI);
      if (theCMSdslFactory != null)
      {
        return theCMSdslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new CMSdslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CMSdslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case CMSdslPackage.PROJECT: return createProject();
      case CMSdslPackage.PRIMARY_ELEMENT: return createPrimaryElement();
      case CMSdslPackage.DB_CONFIG: return createDBConfig();
      case CMSdslPackage.DB_DECL: return createDBDecl();
      case CMSdslPackage.ENTITY: return createEntity();
      case CMSdslPackage.ENTITY_MODEL: return createEntityModel();
      case CMSdslPackage.ENTITY_SERVICE: return createEntityService();
      case CMSdslPackage.FIELD: return createField();
      case CMSdslPackage.FIELD_PROP: return createFieldProp();
      case CMSdslPackage.DATA_TYPE: return createDataType();
      case CMSdslPackage.LIB: return createLib();
      case CMSdslPackage.HOST: return createHost();
      case CMSdslPackage.PORT: return createPort();
      case CMSdslPackage.DIALECT: return createDialect();
      case CMSdslPackage.USER: return createUser();
      case CMSdslPackage.PASS: return createPass();
      case CMSdslPackage.DEF: return createDef();
      case CMSdslPackage.PROP_TEST: return createPropTest();
      case CMSdslPackage.STR: return createStr();
      case CMSdslPackage.DT: return createDt();
      case CMSdslPackage.INTEG: return createInteg();
      case CMSdslPackage.LNG: return createLng();
      case CMSdslPackage.BOOL: return createBool();
      case CMSdslPackage.FLT: return createFlt();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Project createProject()
  {
    ProjectImpl project = new ProjectImpl();
    return project;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PrimaryElement createPrimaryElement()
  {
    PrimaryElementImpl primaryElement = new PrimaryElementImpl();
    return primaryElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DBConfig createDBConfig()
  {
    DBConfigImpl dbConfig = new DBConfigImpl();
    return dbConfig;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DBDecl createDBDecl()
  {
    DBDeclImpl dbDecl = new DBDeclImpl();
    return dbDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Entity createEntity()
  {
    EntityImpl entity = new EntityImpl();
    return entity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EntityModel createEntityModel()
  {
    EntityModelImpl entityModel = new EntityModelImpl();
    return entityModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EntityService createEntityService()
  {
    EntityServiceImpl entityService = new EntityServiceImpl();
    return entityService;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Field createField()
  {
    FieldImpl field = new FieldImpl();
    return field;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FieldProp createFieldProp()
  {
    FieldPropImpl fieldProp = new FieldPropImpl();
    return fieldProp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DataType createDataType()
  {
    DataTypeImpl dataType = new DataTypeImpl();
    return dataType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Lib createLib()
  {
    LibImpl lib = new LibImpl();
    return lib;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Host createHost()
  {
    HostImpl host = new HostImpl();
    return host;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Port createPort()
  {
    PortImpl port = new PortImpl();
    return port;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Dialect createDialect()
  {
    DialectImpl dialect = new DialectImpl();
    return dialect;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public User createUser()
  {
    UserImpl user = new UserImpl();
    return user;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Pass createPass()
  {
    PassImpl pass = new PassImpl();
    return pass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Def createDef()
  {
    DefImpl def = new DefImpl();
    return def;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PropTest createPropTest()
  {
    PropTestImpl propTest = new PropTestImpl();
    return propTest;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Str createStr()
  {
    StrImpl str = new StrImpl();
    return str;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Dt createDt()
  {
    DtImpl dt = new DtImpl();
    return dt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Integ createInteg()
  {
    IntegImpl integ = new IntegImpl();
    return integ;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Lng createLng()
  {
    LngImpl lng = new LngImpl();
    return lng;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Bool createBool()
  {
    BoolImpl bool = new BoolImpl();
    return bool;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Flt createFlt()
  {
    FltImpl flt = new FltImpl();
    return flt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CMSdslPackage getCMSdslPackage()
  {
    return (CMSdslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static CMSdslPackage getPackage()
  {
    return CMSdslPackage.eINSTANCE;
  }

} //CMSdslFactoryImpl
