/**
 * generated by Xtext 2.22.0
 */
package jope015.mdsd2021.reexam.cMSdsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jope015.mdsd2021.reexam.cMSdsl.Entity#getName <em>Name</em>}</li>
 *   <li>{@link jope015.mdsd2021.reexam.cMSdsl.Entity#getRelationship <em>Relationship</em>}</li>
 *   <li>{@link jope015.mdsd2021.reexam.cMSdsl.Entity#getMembers <em>Members</em>}</li>
 * </ul>
 *
 * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getEntity()
 * @model
 * @generated
 */
public interface Entity extends PrimaryElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getEntity_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link jope015.mdsd2021.reexam.cMSdsl.Entity#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Relationship</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationship</em>' containment reference.
   * @see #setRelationship(Relationship)
   * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getEntity_Relationship()
   * @model containment="true"
   * @generated
   */
  Relationship getRelationship();

  /**
   * Sets the value of the '{@link jope015.mdsd2021.reexam.cMSdsl.Entity#getRelationship <em>Relationship</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relationship</em>' containment reference.
   * @see #getRelationship()
   * @generated
   */
  void setRelationship(Relationship value);

  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference list.
   * The list contents are of type {@link jope015.mdsd2021.reexam.cMSdsl.EntityDecl}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference list.
   * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getEntity_Members()
   * @model containment="true"
   * @generated
   */
  EList<EntityDecl> getMembers();

} // Entity
