/**
 * generated by Xtext 2.22.0
 */
package jope015.mdsd2021.reexam.cMSdsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jope015.mdsd2021.reexam.cMSdsl.EntityModel#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getEntityModel()
 * @model
 * @generated
 */
public interface EntityModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link jope015.mdsd2021.reexam.cMSdsl.Field}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getEntityModel_Fields()
   * @model containment="true"
   * @generated
   */
  EList<Field> getFields();

} // EntityModel
