/**
 * generated by Xtext 2.22.0
 */
package jope015.mdsd2021.reexam.cMSdsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jope015.mdsd2021.reexam.cMSdsl.Field#isDontShow <em>Dont Show</em>}</li>
 *   <li>{@link jope015.mdsd2021.reexam.cMSdsl.Field#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getField()
 * @model
 * @generated
 */
public interface Field extends EntityDecl, ParamOrArg
{
  /**
   * Returns the value of the '<em><b>Dont Show</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dont Show</em>' attribute.
   * @see #setDontShow(boolean)
   * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getField_DontShow()
   * @model
   * @generated
   */
  boolean isDontShow();

  /**
   * Sets the value of the '{@link jope015.mdsd2021.reexam.cMSdsl.Field#isDontShow <em>Dont Show</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dont Show</em>' attribute.
   * @see #isDontShow()
   * @generated
   */
  void setDontShow(boolean value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link jope015.mdsd2021.reexam.cMSdsl.FieldProp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getField_Properties()
   * @model containment="true"
   * @generated
   */
  EList<FieldProp> getProperties();

} // Field
