/**
 * generated by Xtext 2.22.0
 */
package jope015.mdsd2021.reexam.cMSdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Port</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jope015.mdsd2021.reexam.cMSdsl.Port#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getPort()
 * @model
 * @generated
 */
public interface Port extends DBDecl
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getPort_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link jope015.mdsd2021.reexam.cMSdsl.Port#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // Port
