/**
 * generated by Xtext 2.22.0
 */
package jope015.mdsd2021.reexam.cMSdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getPrimaryElement()
 * @model
 * @generated
 */
public interface PrimaryElement extends EObject
{
} // PrimaryElement
