/**
 * generated by Xtext 2.22.0
 */
package jope015.mdsd2021.reexam.cMSdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prop Test</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage#getPropTest()
 * @model
 * @generated
 */
public interface PropTest extends FieldProp
{
} // PropTest
