/*
 * generated by Xtext 2.22.0
 */
package jope015.mdsd2021.reexam.validation

import org.eclipse.xtext.validation.Check
import jope015.mdsd2021.reexam.cMSdsl.CMSdslPackage
import jope015.mdsd2021.reexam.cMSdsl.Project
import javax.inject.Inject

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class CMSdslValidator extends AbstractCMSdslValidator {
	
	@Inject extension DBConfigValidator
	
	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkProjectStartsWithCapital(Project project) {
		if (!Character.isUpperCase(project.name.charAt(0))) {
			warning('Name should start with a capital', 
					CMSdslPackage.Literals.PROJECT__NAME,
					INVALID_NAME)
		}
	}
	
}
