/*
 * generated by Xtext 2.22.0
 */
package jope015.mdsd2021.reexam.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCMSdslScopeProvider extends DelegatingScopeProvider {
}
