/*
 * generated by Xtext 2.22.0
 */
package jope015.mdsd2021.reexam.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CMSdslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("jope015/mdsd2021/reexam/parser/antlr/internal/InternalCMSdslParser.tokens");
	}
}
