/*
 * generated by Xtext 2.22.0
 */
package jope015.mdsd2021.reexam.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class CMSdslUiModule extends AbstractCMSdslUiModule {
}
